# Generated by Django 4.2.30 on 2026-07-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_cours', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('volume_horaire', models.IntegerField(default=0)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='accounts.enseignant')),
                ('groupes', models.ManyToManyField(blank=True, related_name='cours', to='accounts.groupe')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.cours')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.groupe')),
            ],
            options={
                'verbose_name': 'Session de cours',
                'verbose_name_plural': 'Sessions de cours',
                'ordering': ['-date_session', 'heure_debut'],
            },
        ),
    ]
