# Generated by Django 4.2.30 on 2026-07-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('absence', 'Absence'), ('retard', 'Retard'), ('rapport', 'Rapport'), ('info', 'Information')], default='info', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('envoyee_le', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.parent')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-envoyee_le'],
            },
        ),
    ]
